name: deployment workflow
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Deploy to prod
        run: echo "Deploying to production..."
